Repository ODOA-Project/ODOA, pull requests merged in 2022-11, with the labels that each got.

#10 [2022-10-27] LFU Cache Python
  .gitignore
  LFU Cache/LFU_Cache.py
  README.md
Labels: ODOA, Hard

#12 [2022-10-28] Longest Common Prefix Swift
   Longest Common Prefix/LongestCommonPrefix.swift
  README.md
Labels: ODOA, easy

#13 [2022-11-01] Remove Duplicates from Sorted Array Python
  README.md
  Remove Duplicates from Sorted Array/remove_duplicates_from_sorted_array.py
Labels: ODOA, easy

#11 [2022-10-28] Merge Two Sorted Lists Python
  Merge Two Sorted Lists/merge_two_sorted_list.py
  README.md
Labels: ODOA, easy

#20 [2022-11-02] Merge Two Sorted Lists Swift
  Merge Two Sorted Lists/Merge_Two_Sorted_Lists.swift
  README.md
Labels: ODOA, easy

#18 [2022-11-03] Roman to Integer C++
  README.md
  Roman to Integer/Roman to Integer.cpp
Labels: ODOA, easy

#22 [2022-11-03] Search Insert Position Python
  README.md
  Search Insert Position/Search Insert Position.py
Labels: ODOA, Easy

#21 [2022-11-03] Remove Duplicates from Sorted Array Swift
  README.md
  Remove Duplicates from Sorted Array/Remove_Duplicates_from_Sorted_Array.swift
Labels: ODOA, Easy

#23 [2022-11-03] Longest Common Prefix C++
  Longest Common Prefix/Longest_Common_Prefix.cpp
  README.md
Labels: ODOA, Easy

#19 [2022-11-03] Number Of Steps To Reduce A Number To Zero Python
  Number Of Steps To Reduce A Number To Zero/number_of_steps_to_reduce_a_number_to_zero.py
  README.md
Labels: ODOA, Easy

#31 [2022-11-08] Merge Sorted Array Python
  Merge Sorted Array/Merge Sorted Array.py
  README.md
Labels: ODOA, Easy

#30 [2022-11-06] Merge Two Sorted Lists C++
  Merge Two Sorted Lists/Merge_Two_Sorted_Lists.cpp
  README.md
Labels: ODOA, Easy

#26 [2022-11-04] Longest Common Prefix Python
  Flood Fill/flood_fill.py
  Longest Common Prefix/longest_common_prefix.py
  README.md
Labels: ODOA, Easy
